### ISSUE TITLE
Adding Security Questions to other Pages before Activities ie Lessons, Quizzes

### ISSUE THREAD

**Issue by EFoster1068** [catalyst/moodle-tool_securityquestions#61]
In the README file it states:

The last thing to check is to go back to the plugin admin settings, and select all of the pages that users should be prompted security questions on.

However I have not been able to find a location where this choice of optioning is available.

I am new to this and trying to learn as fast as possible for my company LMS to run accordingly.

**Comment by brendanheywood** [comment]
I'm not sure this is the best place for this? These security questions are around confirming your identity when you have forgotten your password, or perhaps later with our multi factor auth plugin so you need to confirm them when logging it.

It doesn't seem appropriate to ask people for these before a quiz?

I'm guessing what you want is more like activity availability conditions:

https://docs.moodle.org/38/en/Restrict_access

https://docs.moodle.org/dev/Availability_conditions

https://moodle.org/plugins/browse.php?list=category&id=57

**Comment by EFoster1068** [comment]
The government agencies that we are involved with require such identity verification of the users.  I read the README file and it made it sound like this could be adjusted for more than just the password change page hence my question to the developers.

**Comment by brendanheywood** [comment]
This security check sounds like something that should happen when they login, not when they start a particular quiz.

If it is at login time, then this sounds more like you want multi factor authentication, in which case this plugin is probably more want you want:

https://github.com/catalyst/moodle-tool_mfa

We do have the ability to use the security questions set via this plugin as a potential factor for use in the MFA plugin. See this issue:

https://github.com/catalyst/moodle-tool_mfa/issues/13

This would mean that when they login, they have to provide their password and then answer their security questions in order to login. Then they can go to any quiz / lesson etc.

If it is definitely only at the time they start the quiz then this should be an availability condition. You could write an availability condition wrapper which leverages this plugin. But honestly that sounds like an awful user experience and doesn't sound right to me.

**Comment by brendanheywood** [comment]
Also if you want to sponsor, or make a pull request for issue 13 in MFA that would be most welcome.
